name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
jobs:
  package:
    runs-on: windows-latest

    steps:
      - run: rustup --version

      - uses: briansmith/actions-checkout@v4
        with:
          persist-credentials: false

      - run: ./mk/install-build-tools.ps1

      - run: echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin" >> $GITHUB_PATH
        shell: bash

      - run: sh mk/package.sh
        shell: bash
